name: prinstpl_php_array_vs_object_benchmark

services:
  php_74:
    build:
      args:
        - PHP_VER=7.4
        - PROJECT_DIR=${PROJECT_DIR:-/opt/project}
      context: .
      dockerfile: Dockerfile
    cpu_count: 1
    volumes:
      - ./src:${PROJECT_DIR:-/opt/project}:ro
  php_80:
    build:
      args:
        - PHP_VER=8.0
        - PROJECT_DIR=${PROJECT_DIR:-/opt/project}
      context: .
      dockerfile: Dockerfile
    cpu_count: 1
    volumes:
      - ./src:${PROJECT_DIR:-/opt/project}:ro
  php_81:
    build:
      args:
        - PHP_VER=8.1
        - PROJECT_DIR=${PROJECT_DIR:-/opt/project}
      context: .
      dockerfile: Dockerfile
    cpu_count: 1
    volumes:
      - ./src:${PROJECT_DIR:-/opt/project}:ro
  php_82:
    build:
      args:
        - PHP_VER=8.2
        - PROJECT_DIR=${PROJECT_DIR:-/opt/project}
      context: .
      dockerfile: Dockerfile
    cpu_count: 1
    volumes:
      - ./src:${PROJECT_DIR:-/opt/project}:ro
  php_83:
    build:
      args:
        - PHP_VER=8.3
        - PROJECT_DIR=${PROJECT_DIR:-/opt/project}
      context: .
      dockerfile: Dockerfile
    cpu_count: 1
    volumes:
      - ./src:${PROJECT_DIR:-/opt/project}:ro
